### ISSUE TITLE
ebay-promised usage

### ISSUE THREAD

**Issue by gunonmove** [ondreian/ebay-promised#1]
I am not sure this is right place for this.
I start to use your module: ebay-promised
This module is simply great, anyway I could not find enought documentation about this.

For Instance how could I use a nested option? 
for example I would like to get active listing, using: getMyeBaySelling
In this situation I should set

``` xml
<ActiveList>
  <Include>true</Include>
</ActiveList>
```

How to translate this in nodejs?

``` javascript
.getMyeBaySelling()    
.activeList.input(true)
.invoke()                  
.fail(function(data){
    console.log('Error');
})          
.then(function(data){
    //console.log(data);
    res.send(data);
})
```

This code i just above fails...

Thank you

**Comment by ondreian** [comment]
@gunonmove I'm glad you're finding it useful.  Given that there is a myriad of configuration options that can be passed into all of the api calls, I opted not to make those options chainable like that.  In this instance you would need to pass the json representation of the configuration you want inside of the "activeList" portion of the api call.

``` javascript
// set up an ebay object with the appropriate config info
ebay          = new Ebay(config.production)
ebay.serviceName("Trading")

// let's start building the api call
 ebay
    .getMyeBaySelling()
    .activeList({ Include: true }) // notice the capitalization, Ebay XML nodes are case sensitive
    .invoke()
    .fail(handleError)
    .then(function(data){
       console.log(data);
    });
```

To help you visualize the underlying SOAP request with Ebay resulting XML for this request would be like:

``` xml
<xml version="1.0" encoding="utf-8"? />
<GetMyeBaySellingRequest xmlns="urn:ebay:apis:eBLBaseComponents">
  <RequesterCredentials>
    # your credentials
  </RequesterCredentials>
  <ActiveList>
    <Include>true</Include>
    <Pagination>
      <PageNumber>1</PageNumber>
      <EntriesPerPage>100</EntriesPerPage>
    </Pagination>
  </ActiveList>
</GetMyeBaySellingRequest>
```

The important part to notice is the `<Include>` node is nested within the `<activeList>` node.

**Comment by gunonmove** [comment]
Thank you is exactly what I was looking for.
