### ISSUE TITLE
Issue with normalizeResponse

### ISSUE THREAD

**Issue by safebyte** [ondreian/ebay-promised#2]
When doing multiple api requests at the same time, `utils.normalizeResponse` will fail with:

```
 Possibly unhandled TypeError: Cannot convert undefined or null to object
     at Ebay.utils.normalizeResponse
```

Is it possible to do parallel requests?

**Comment by ondreian** [comment]
It is possible to do parallel requests. 

Are you using the same instance of the Ebay object for all of your parallel requests?

If you are, and using that instance to invoke a request that is different from the first, it changes the internals for the parser.

What I imagine is likely happening is your current flow is running something like this:

```
- create first new Ebay instance
---- invoke a longer request with Ebay   ex: "GetCategories"
---- invoke a shorter different request     ex: "VerifyRelistItem"
--------- Second request finished
--------- First request finishes, but the internals for Ebay to parse the response have been modified
-------------- Script fails with your error
```

If this is the case, then you should have a function which returns your a new instance of the Ebay object.

spawn-ebay-request.coffee

``` coffeescript
Ebay = require 'ebay-promised'
config = require './your/config'

module.exports = ()->
  new Ebay(config)
```

requests.coffee

``` coffeescript
ebay = require('./spawn-ebay-request')

# these will run in parallel 
req1 = ebay().getCategories().invoke().then(handle)
req2 = ebay().getSellerList().invoke().then(handle2)

```

If you are already doing this, it could also be possible that your request is some very odd edge case I didn't account for in the various permutations of the possible requests.

If so, might you share an example of the request you are making (sans your credentials obviously)?

**Comment by safebyte** [comment]
Solid answer. Using a new instance solved it for me.
I really appreciate your work, thank you!

**Comment by ondreian** [comment]
@safebyte Glad it worked.
