### ISSUE TITLE
ListingType field becomes a List instead of string

### ISSUE THREAD

**Issue by tabzone** [ondreian/ebay-promised#47]
for getorder pass ListingType it becomes -

  </RequesterCredentials>
  <CreateTimeFrom>2017-05-13T20:34:44.000Z</CreateTimeFrom>
  <ListingType>
    <0>1</0>
    <Pagination>
      <PageNumber>1</PageNumber>
      <EntriesPerPage>100</EntriesPerPage>
    </Pagination>
  </ListingType>
</GetOrdersRequest>

issue is in 

 /**
   * determines if the Request uses a List and which key it is
   *
   * @private
   * @return     {string|false}   the key that is a List  
   */
  listKey () {
    const fields = this.fieldKeys
    while (fields.length) {
      const field = fields.pop()
      if ( ~field.indexOf(LIST) ) return field
    }
    return false
  }

**Comment by ondreian** [comment]
Thanks for reporting this.  I'll see about getting a bug release early next week out.

**Comment by ondreian** [comment]
@tabzone should be fixed in `2.3.0` release.

please reopen if you find it's not
