### ISSUE TITLE
shipment tracking numbers, and prices, maybe other fields, do not return correctly

### ISSUE THREAD

**Issue by ericblade** [ondreian/ebay-promised#51]
Example Shipment Tracking Number from GetOrders():

````
....
                        "SellingManagerSalesRecordNumber": 119,
                        "ShipmentTrackingDetails": {
                            "ShippingCarrierUsed": "USPS",
                            "ShipmentTrackingNumber": 9.400109699939589e+21
                        }
                    },
....
````
Looks like a forced conversion to int for a value that should be a string.  

Also, prices are returned by APIs as float or int ($20.00 => 20, $19.99 = 19.99).  Currency values should always be handled either directly in string, or in an integer of the lowest unit (in USD, that would be 'cents' for most applications), so $20.00 => 2000, $19.99 => 1999 .. or $20.00 => "20.00", $19.99 => "19.99".

**Comment by ondreian** [comment]
Good catch. PRS are welcome, i unfortunately do not have time this month to work on this bug.  I think either is a valid solution, string seems less prescriptive and I would prefer not to introduce the complexity of a true currency parser.

**Comment by ericblade** [comment]
Yeah.. I'm not familiar enough with the ebay API (wow is it a mess in places :) ) to know right off how to approach conversion . . for currencies that use a period for decimal, it's pretty easy, I'm not sure however if ebay localizes any of their output, and it might be possible to run into output that uses a comma as the decimal separator, or what not.  

For the simple case, works with period-decimal string and float:

````(fl) => Math.abs(Math.round(parseFloat(fl).toFixed(2) * 100))````

(the abs call I use to make sure all the numbers I store are positive)

So, I think probably the best approach for this, and probably for #50 as well (I would've combined them, but I was going through different call data at different times.. I should've just edited #50 .. oh well. I guess i'll edit this one and close that one) .. would be to just not convert anything to int/float, and leave it up to the consumer of the library.

  at least, I'm assuming that this library is doing it somewhere.  If you'd rather the conversion remained for certain keys, I'd probably consider a whitelist for keys that are known to be safely convertible, rather than a blacklist, considering that it's probably possible for ebay to add new keys to the output.

 I can probably take a look at it, might take me a bit to become familiar with the repo, though.

**Comment by ondreian** [comment]
All of the type casting currentl happens inside of [`Parser.cast`](https://github.com/ondreian/ebay-promised/blob/master/es6/Parser.js#L42-L61).

I agree it probably makes sense to just do away with Number casting, it seems to be fraught with perils, and would be a real pain to autogenerate all of the types from the documentation. 

This feels like a breaking change at either rate since we are changing the way data will be returned, but I agree it's probably for the best.

**Comment by ericblade** [comment]
I appreciate your input. I'll probably see what I can come up with for a PR this evening, so I can get prices and tracking numbers to come back correctly as strings.  As far as whitelisting, I can implement a white list, but I don't know what keys I should put in it, I really haven't gone through the entire API, I'm just trying to implement a few calls here and there to pull sales data into a database.  And, yeah, it's probably better to do a major version bump, than to return numeric tracking numbers for USPS :-)

**Comment by ericblade** [comment]
hey @ondreian so I'm looking at it, and it looks like it's just as simple as removing the line in cast that converts to number.  Do you *want* me to put in a whitelist, following the same pattern as dateNodes ?  I don't know specifically what keys would be wanting for that, so I'd be leaving it empty pending further input/research.

I'm going to go ahead and submit a PR with it removed, and we can discuss further if necessary.

**Comment by ondreian** [comment]
i think the best place to start is just reducing the amount of bad type casts for now.  

The only keys that should be cast to `Number` for sure are quantity keys (inventory counts for instance), but as you've noted this can be a PITA to deal with due to the numerous varied names that exist, and it's likely to be more confusing if we are only casting some of them to `Number`.

to sum it up, perhaps it's best that casting does not happen by default at all, beyond mapping array-like keys to `Array` so that they can be worked with reasonably well.

**Comment by ericblade** [comment]
... ok, getting tests to run seems to be a bit more involved than I am able to put in right at this moment, in that i didn't bother to configure sandbox (ok maybe i'm dumb, but i'm only doing queries, not creates/updates right now) .. if you don't mind, i'm going to put in a section in the readme about how to build/test, since i just had to dig into the code to figure that out.  anyway, i'll submit a PR with it not casting to Number sometime soon.

**Comment by ondreian** [comment]
that's fine, the tests are a bit dicey right now and were really just a work-in-progress when it was decided I should migrate this service to Elixir.

**Comment by ondreian** [comment]
I'll get these PRs merged this evening and hopefully have time to publish a major version bump as well, thanks!

**Comment by ericblade** [comment]
cool :) you might want to hop over to the Travis config, and paste your keys into the settings as environment variables, rather than having the encrypted js file in the repo, there's an option to hide your environment variables from the output, so observers can't grab them.  At least, that's how I'd fix the Travis builder issue .. if you have a better idea, though, that's cool too.  My Amazon API tests via Travis using environment variables for the access keys, and that works well.

**Comment by ondreian** [comment]
The docs seems to suggest they are more or less equivalent, since neither is going to be exposed to untrusted builds?  I guess it would be good for keeping the repo itself clean.

**Comment by ericblade** [comment]
ah, didn't realize that was a documented method. well, it doesn't like the command line that it's receiving.. so something needs a fix to make it work .. :-)  I am the typical person who does first, then reads the instructions if it fails ;-) , so I didn't realize they (travis) suggested doing that.
